[package]
name = "metaframer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
assert_cmd = "2.0.14"
clap = { version = "4", features = ["derive"] }
clap_derive = { version = "4.0.0-rc.1" } 
image = "0.25.1"
imageproc = "0.25.0"
kamadak-exif = "0.5.5"
predicates = "3.1.0"
